steps:
  # Run tests before building
  - name: 'python:3.13-slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m pytest

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/document-classifier:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/document-classifier:latest'
      - '.'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/document-classifier:$COMMIT_SHA']
  
  # Also tag as latest for cache usage in future builds
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/document-classifier:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/document-classifier:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/document-classifier:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'document-classifier'
      - '--image'
      - 'gcr.io/$PROJECT_ID/document-classifier:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1'

images:
  - 'gcr.io/$PROJECT_ID/document-classifier:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/document-classifier:latest'

timeout: '1800s'
